import {
  EmailNotificationService,
  RequestNotificationParams,
  EmailResult,
} from './adapter';

export class EmailNotificationServiceImpl implements EmailNotificationService {
  private provider: string;
  private apiKey: string;
  private recipient: string;

  constructor() {
    this.provider = (process.env.EMAIL_PROVIDER || 'resend').toLowerCase();
    this.apiKey = process.env.EMAIL_PROVIDER_API_KEY || '';
    this.recipient = process.env.EMAIL_NOTIFICATION_RECIPIENT || 'egypt_nationaltours@yahoo.com';
  }

  /**
   * Format structured HTML email for notification recipient.
   */
  private formatHtmlEmail(params: RequestNotificationParams): string {
    const detailsRows = Object.entries(params.details)
      .map(([key, val]) => {
        const valueString =
          typeof val === 'object' && val !== null ? JSON.stringify(val, null, 2) : String(val ?? '');
        return `
          <tr>
            <td style="padding: 8px; border: 1px solid #e5e7eb; font-weight: bold; background-color: #f9fafb;">${key}</td>
            <td style="padding: 8px; border: 1px solid #e5e7eb;">${valueString}</td>
          </tr>
        `;
      })
      .join('');

    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>New Service Request - ${params.reference}</title>
        </head>
        <body style="font-family: Arial, sans-serif; color: #1f2937; line-height: 1.6; margin: 0; padding: 20px;">
          <div style="max-width: 600px; margin: 0 auto; background: #ffffff; border: 1px solid #d1d5db; border-radius: 8px; overflow: hidden;">
            <div style="background-color: #990000; color: #ffffff; padding: 20px; text-align: center;">
              <h1 style="margin: 0; font-size: 20px;">New Request: ${params.reference}</h1>
              <p style="margin: 5px 0 0 0; font-size: 14px;">Egypt National Tours — ${params.requestType.toUpperCase()}</p>
            </div>
            
            <div style="padding: 20px;">
              <h2 style="font-size: 16px; border-bottom: 2px solid #d4af37; padding-bottom: 5px; color: #990000;">Customer Contact Information</h2>
              <p style="margin: 4px 0;"><strong>Name:</strong> ${params.customerName}</p>
              <p style="margin: 4px 0;"><strong>Email:</strong> <a href="mailto:${params.customerEmail}">${params.customerEmail}</a></p>
              <p style="margin: 4px 0;"><strong>Phone / WhatsApp:</strong> ${params.customerPhone}</p>
              <p style="margin: 4px 0;"><strong>Date:</strong> ${params.timestamp}</p>

              <h2 style="font-size: 16px; border-bottom: 2px solid #d4af37; padding-bottom: 5px; color: #990000; margin-top: 20px;">Request Payload Details</h2>
              <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
                ${detailsRows}
              </table>
            </div>

            <div style="background-color: #f3f4f6; padding: 12px; text-align: center; font-size: 12px; color: #6b7280;">
              This is an automated request alert generated by Egypt National Tours Website System.
            </div>
          </div>
        </body>
      </html>
    `;
  }

  async sendRequestNotification(params: RequestNotificationParams): Promise<EmailResult> {
    // 1. If API key is missing, safely skip sending without crashing
    if (!this.apiKey || this.apiKey.trim() === '') {
      console.log(
        `[EmailAdapter] SKIPPED (No API key in env): New request ${params.reference} from ${params.customerEmail}`
      );
      return {
        success: false,
        status: 'skipped_no_credentials',
        error: 'EMAIL_PROVIDER_API_KEY is not configured in environment',
        provider: this.provider,
      };
    }

    // 2. Dispatch email via Resend API
    if (this.provider === 'resend') {
      try {
        const response = await fetch('https://api.resend.com/emails', {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            from: 'Egypt National Tours <requests@egyptnationaltours.com>',
            to: [this.recipient],
            subject: `[New Request ${params.reference}] ${params.requestType.toUpperCase()} - ${params.customerName}`,
            html: this.formatHtmlEmail(params),
          }),
        });

        if (!response.ok) {
          const errorData = await response.json();
          throw new Error(errorData.message || `Resend API returned status ${response.status}`);
        }

        return {
          success: true,
          status: 'sent',
          provider: 'resend',
        };
      } catch (err: any) {
        console.error('[EmailAdapter] Delivery Error:', err.message);
        return {
          success: false,
          status: 'failed',
          error: err.message || 'Failed to deliver email notification',
          provider: 'resend',
        };
      }
    }

    // Fallback for unsupported provider
    return {
      success: false,
      status: 'skipped_no_credentials',
      error: `Unsupported EMAIL_PROVIDER: ${this.provider}`,
      provider: this.provider,
    };
  }
}

export const emailNotificationService = new EmailNotificationServiceImpl();
